#!/bin/bash

mkdir build
cd build

declare -a CMAKE_PLATFORM_FLAGS
if [[ ${HOST} =~ .*linux.* ]]; then
    CMAKE_PLATFORM_FLAGS+=(-DCMAKE_TOOLCHAIN_FILE="${RECIPE_DIR}/cross-linux.cmake")
fi

export BOOST_ROOT=$PREFIX
export GLFW3_ROOT=$PREFIX
export TBB_ROOT=$PREFIX
export ILMBASE_ROOT=$PREFIX
export OPENEXR_ROOT=$PREFIX
export BLOSC_ROOT=$PREFIX

cmake $SRC_DIR -G "Ninja" \
    -DOPENEXR_NAMESPACE_VERSIONING:BOOL=OFF \
    -DILMBASE_NAMESPACE_VERSIONING:BOOL=OFF \
    -DUSE_GLFW3:BOOL=ON \
    -DOPENVDB_BUILD_UNITTESTS:BOOL=OFF \
    -DOPENVDB_BUILD_PYTHON_MODULE:BOOL=OFF \
    -DOPENVDB_ENABLE_3_ABI_COMPATIBLE:BOOL=OFF \
    -DBUILD_SHARED_LIBS:BOOL=ON \
    -DCMAKE_CXX_FLAGS:STRING="-std=c++11" \
    -DCMAKE_BUILD_TYPE:STRING=Release \
    -DCMAKE_INSTALL_PREFIX:PATH=$PREFIX \
    ${CMAKE_PLATFORM_FLAGS[@]}

ninja install
