{% set name = "openvdb" %}
{% set version = "5.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/AcademySoftwareFoundation/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 86b3bc51002bc25ae8d69991228228c79b040cb1a5803d87543b407645f6ab20

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libxi-devel') }}           # [linux]
    - {{ cdt('libxrandr-devel') }}       # [linux]
    - {{ cdt('libxinerama-devel') }}     # [linux]
    - {{ cdt('libxcursor-devel') }}      # [linux]
    - {{ cdt('libxxf86vm-devel') }}      # [linux]
    - {{ cdt('libxcb') }}                # [linux]
    - {{ cdt('libselinux-devel') }}      # [linux]
    - {{ cdt('libxext-devel') }}         # [linux]
    - {{ cdt('libxdamage') }}            # [linux]
    - {{ cdt('libxfixes') }}             # [linux]
    - {{ cdt('libxrender-devel') }}      # [linux]
    - {{ cdt('libxau-devel') }}          # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
  host:
    - openexr
    - glfw3
    - blosc
    - tbb ==2018.0.2
    - boost
    - libglu                          # [linux]
    - glibc214
  run:
    - openexr
    - glfw3
    - blosc
    - tbb ==2018.0.2
    - boost
    - libglu                          # [linux]

about:
  home: http://www.openvdb.org/
  license: MPL-2.0
  license_file: LICENSE
  summary: Sparse volume data structure and tools.
  description: |
    OpenVDB is an open source C++ library comprising a novel hierarchical data
    structure and a large suite of tools for the efficient storage and
    manipulation of sparse volumetric data discretized on three-dimensional
    grids. It is developed and maintained by DreamWorks Animation for use in
    volumetric applications typically encountered in feature film production.
  doc_url: http://www.openvdb.org/documentation/
  dev_url: https://github.com/AcademySoftwareFoundation/openvdb

extra:
  recipe-maintainers:
    - aaronang
