{% set name = "openvdb" %}
{% set version = "5.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/AcademySoftwareFoundation/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 86b3bc51002bc25ae8d69991228228c79b040cb1a5803d87543b407645f6ab20

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - openexr
    - glfw3
    - blosc
    - tbb ==2018.0.2
    - boost
  run:
    - openexr
    - glfw3
    - blosc
    - tbb ==2018.0.2
    - boost

about:
  home: http://www.openvdb.org/
  license: MPL-2.0
  license_file: LICENSE
  summary: Sparse volume data structure and tools.
  description: |
    OpenVDB is an open source C++ library comprising a novel hierarchical data
    structure and a large suite of tools for the efficient storage and
    manipulation of sparse volumetric data discretized on three-dimensional
    grids. It is developed and maintained by DreamWorks Animation for use in
    volumetric applications typically encountered in feature film production.
  doc_url: http://www.openvdb.org/documentation/
  dev_url: https://github.com/AcademySoftwareFoundation/openvdb

extra:
  recipe-maintainers:
    - aaronang
