version: 2
jobs:
  build:
    docker:
      - image: conda/miniconda3
    steps:
      - checkout
      - run: |
          apt-get update
          apt-get install --yes binutils
      - run: |
          conda install --yes conda-build
          conda update --yes conda conda-build
          conda list
      - run: conda build recipe -c aaronang -c menpo -c conda-forge
