version: 2
jobs:
  build:
    docker:
      - image: conda/miniconda3
    steps:
      - checkout
      - run: |
          apt-get update
          apt-get install --yes binutils
      - run: |
          conda install --yes conda-build
          conda update --yes conda conda-build
      - run: |
          mkdir -p /opt/graphics/OpenGL/lib
          ln -s /usr/lib/x86_64-linux-gnu/libGLU.so /opt/graphics/OpenGL/lib
      - run: conda build recipe -c aaronang -c menpo -c conda-forge
